spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/pet_product_db
    username: user
    password: user
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    database: postgresql
  kafka:
    producer:
      client-id: "product-service-producer"

server:
  port: 8081

product:
  discount:
    status: false
application:
  kafka:
    topic: supplier-request-event

broker:
  bootstrap-servers: localhost:9092