spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/pet_product_db
    username: user
    password: user
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    database: postgresql
server:
  port: 8081

product:
  discount:
    status: false
